config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/band.rb
class Band < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :session_token, presence: true, uniqueness: true
    validates :password, length: {minimum: 6, allow_nil: true}

    attr_reader :password 
    before_validation :ensure_session_token

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)

        if user && user.is_password?(password)
            return user 
        else  
            return nil
        end
    end

    def password=(password)
        @password = password 
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        bcrypt_object = BCrypt::Password.new(self.password_digest)
        bcrypt_object.is_password?(password)
    end

    def reset_session_token
        self.session_token = generate_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token 
        self.session_token ||= generate_session_token
    end

    private
    def generate_session_token
        token = SecureRandom::urlsafe_base64
        while User.exists?(session_token: token)
            token = SecureRandom::urlsafe_base64
        end
        token
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logout, :logged_in?

    def current_user 
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def require_logged_out
        redirect_to users_url if logged_in?
    end

    def logged_in?
        !!current_user
    end

    def login(user)
        session[:session_token] = user.reset_session_token
    end

    def logout 
        current_user.reset_session_token if logged_in?
        session[:session_token] = nil 
        @current_user = nil
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    #login
    def create
        email = params[:user][:email]
        password = params[:user][:password]

        @user = User.find_by_credentials(email, password)

        if @user 
            login(@user)
            redirect_to user_url(@user)
        else  
            render :new
        end
    end

    #logout
    def destroy 
        logout 
        redirect_to new_session_url
    end

    #login page
    def new 
        @user = User.new 
        render :new
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
        @user = User.new 
        render :new
    end

    def create 
        @user = User.new(user_params)
        if @user.save 
            redirect_to user_url(@user)
        else  
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show 
        @user = User.find(params[:id])
        render :show
    end

    private 
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

<header>
  <h1> Music App</h1>
</header>

<nav class='sign_buttons'>
 <% if logged_in? %>
    <h2>Welcome back</h2>
    <form action="<%= session_url %>" method='POST'> 
     <input type="hidden" name="authenticity_token" value= '<%= form_authenticity_token %>' >
      <input type="hidden" name="_method" value='DELETE'>
      <button>Log out</button>
    </form>

  <% else %>
    
    <form action="<%= new_session_url %>" method='GET'> 
     <input type="hidden" name="authenticity_token" value= '<%= form_authenticity_token %>' >
      <button>Sign in</button>
    </form>
    <br>
      <form action="<%= new_user_url %>" method='GET'> 
     <input type="hidden" name="authenticity_token" value= '<%= form_authenticity_token %>' >
      <button>Sign up</button>
    </form>

  <% end %>
</nav>

<body>
    <%= yield %>
  

  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <li> <%= error %> </li>
      <br>
    <% end %>
  <% end %>
  
</body>

</html>

app/views/users/show.html.erb
<h2>Account Overview</h2>
<ul>
    <li>Email: <%= @user.email %></li>
</ul>